name: Test Trigger Using GH CLI

run-name: GAM Trigger - ${{ inputs.component }}-${{ inputs.gam_trigger_run_id }}

on:
  workflow_dispatch:
    inputs:
      component:
        type: choice
        description: select component
        options:
          - Dashboard
        required: true
      gam_trigger_repository:
        description: 'Github Repository from which this workflow is triggered (default is current date and time)'
        default: "12345"
        required: true
      gam_trigger_run_id:
        description: 'Workflow Run ID of the Trigger Workflow (default is current date and time)'
        default: "12345"
        required: true
        

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Change Github Actor name
        run: echo "$GITHUB_ACTOR"

      - name: sleep for 1 minute
        run: sleep 60

      - name: Print a message
        run: |
          echo "Hello, this is a workflow triggered by workflow_dispatch!"
          echo "Component: ${{ inputs.component }}"
          echo "GAM Trigger Repository: ${{ inputs.gam_trigger_repository }}"
          echo "Workflow Run ID: ${{ inputs.gam_trigger_run_id }}"
          echo " GAM Trigger Workflow Run: https://github.com/${{ inputs.gam_trigger_repository }}/actions/runs/${{ inputs.gam_trigger_run_id }}"


