name: Test Trigger From GH CLI

run-name: GAM Trigger - ${{ inputs.component }}-${{ inputs.workflow_run_id }}

on:
  workflow_dispatch:
    inputs:
      component:
        type: choice
        description: select component
        options:
          - Dashboard
      workflow_run_id:
        description: 'Execution ID (default is current date and time)'
        default: "12345"
        required: false
        

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Change Github Actor name
        run: echo "$GITHUB_ACTOR"

      - name: sleep for 1 minute
        run: sleep 60

      - name: Print a message
        run: |
          echo "Hello, this is a workflow triggered by workflow_dispatch!"
          echo "Component: ${{ inputs.component }}"
          echo "Workflow Run ID: ${{ inputs.workflow_run_id }}"

